version: "2.2"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    restart: always

  jobinja:
    build: jobinja
    image: jobinja:latest
    ports:
      - 2001:5000
    restart: always
    links:
      - "selenium:selenium"

  jobvision:
    build: jobvision
    image: jobvision:latest
    ports:
      - 2002:5000
    restart: always
    links:
      - "selenium:selenium"
