version: "2.2"
services:

  selenium:
    image: selenium/standalone-chrome:latest
    restart: always

  jobinja:
    build: jobinja
    image: jobinja:latest
    ports:
      - 2001:5000
    restart: always
    links:
      - "selenium:selenium"

  jobvision:
    build: jobvision
    image: jobvision:latest
    ports:
      - 2002:5000
    restart: always
    links:
      - "selenium:selenium"

  telegram_bot:
    build: telegram_bot
    image: telegram_bot:latest
    env_file: 
      - telegram_bot/.env
    ports:
      - 2003:5000
    restart: always
    links: 
      - jobinja:jobinja
      - jobvision:jobvision

